// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ApplicationMgmt.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationDetails struct {
	ApplicationName      string   `protobuf:"bytes,1,opt,name=applicationName,proto3" json:"applicationName,omitempty"`
	OrgName              string   `protobuf:"bytes,2,opt,name=orgName,proto3" json:"orgName,omitempty"`
	Cloud                string   `protobuf:"bytes,3,opt,name=cloud,proto3" json:"cloud,omitempty"`
	AwsAccessKey         string   `protobuf:"bytes,4,opt,name=awsAccessKey,proto3" json:"awsAccessKey,omitempty"`
	AwsSecret            string   `protobuf:"bytes,5,opt,name=awsSecret,proto3" json:"awsSecret,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDetails) Reset()         { *m = ApplicationDetails{} }
func (m *ApplicationDetails) String() string { return proto.CompactTextString(m) }
func (*ApplicationDetails) ProtoMessage()    {}
func (*ApplicationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_5415633a7c372a18, []int{0}
}

func (m *ApplicationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDetails.Unmarshal(m, b)
}
func (m *ApplicationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDetails.Marshal(b, m, deterministic)
}
func (m *ApplicationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDetails.Merge(m, src)
}
func (m *ApplicationDetails) XXX_Size() int {
	return xxx_messageInfo_ApplicationDetails.Size(m)
}
func (m *ApplicationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDetails proto.InternalMessageInfo

func (m *ApplicationDetails) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ApplicationDetails) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *ApplicationDetails) GetCloud() string {
	if m != nil {
		return m.Cloud
	}
	return ""
}

func (m *ApplicationDetails) GetAwsAccessKey() string {
	if m != nil {
		return m.AwsAccessKey
	}
	return ""
}

func (m *ApplicationDetails) GetAwsSecret() string {
	if m != nil {
		return m.AwsSecret
	}
	return ""
}

func (m *ApplicationDetails) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ApplicationCreateResponse struct {
	ApplicationName      string   `protobuf:"bytes,1,opt,name=applicationName,proto3" json:"applicationName,omitempty"`
	ApplicationId        string   `protobuf:"bytes,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationCreateResponse) Reset()         { *m = ApplicationCreateResponse{} }
func (m *ApplicationCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationCreateResponse) ProtoMessage()    {}
func (*ApplicationCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5415633a7c372a18, []int{1}
}

func (m *ApplicationCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationCreateResponse.Unmarshal(m, b)
}
func (m *ApplicationCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationCreateResponse.Marshal(b, m, deterministic)
}
func (m *ApplicationCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationCreateResponse.Merge(m, src)
}
func (m *ApplicationCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationCreateResponse.Size(m)
}
func (m *ApplicationCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationCreateResponse proto.InternalMessageInfo

func (m *ApplicationCreateResponse) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ApplicationCreateResponse) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

type GetApplicationsRequest struct {
	OrgName              string   `protobuf:"bytes,1,opt,name=orgName,proto3" json:"orgName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationsRequest) Reset()         { *m = GetApplicationsRequest{} }
func (m *GetApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationsRequest) ProtoMessage()    {}
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5415633a7c372a18, []int{2}
}

func (m *GetApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationsRequest.Unmarshal(m, b)
}
func (m *GetApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationsRequest.Merge(m, src)
}
func (m *GetApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationsRequest.Size(m)
}
func (m *GetApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationsRequest proto.InternalMessageInfo

func (m *GetApplicationsRequest) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

type GetApplicationsResponse struct {
	Applications         []*ApplicationDetails `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetApplicationsResponse) Reset()         { *m = GetApplicationsResponse{} }
func (m *GetApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplicationsResponse) ProtoMessage()    {}
func (*GetApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5415633a7c372a18, []int{3}
}

func (m *GetApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationsResponse.Unmarshal(m, b)
}
func (m *GetApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *GetApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationsResponse.Merge(m, src)
}
func (m *GetApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplicationsResponse.Size(m)
}
func (m *GetApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationsResponse proto.InternalMessageInfo

func (m *GetApplicationsResponse) GetApplications() []*ApplicationDetails {
	if m != nil {
		return m.Applications
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplicationDetails)(nil), "services.ApplicationDetails")
	proto.RegisterType((*ApplicationCreateResponse)(nil), "services.ApplicationCreateResponse")
	proto.RegisterType((*GetApplicationsRequest)(nil), "services.GetApplicationsRequest")
	proto.RegisterType((*GetApplicationsResponse)(nil), "services.GetApplicationsResponse")
}

func init() { proto.RegisterFile("ApplicationMgmt.proto", fileDescriptor_5415633a7c372a18) }

var fileDescriptor_5415633a7c372a18 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0xc6, 0x5d, 0x11, 0x94, 0x01, 0x43, 0x32, 0xf1, 0x4f, 0x25, 0x1c, 0xd6, 0xea, 0x81, 0x13,
	0x07, 0x7c, 0x01, 0x89, 0x26, 0xc6, 0x18, 0x3c, 0xac, 0x47, 0x4e, 0xb5, 0x4c, 0xc8, 0xc6, 0x85,
	0xae, 0x9d, 0x22, 0xf1, 0xe1, 0x7c, 0x09, 0x9f, 0xc8, 0x50, 0x20, 0x74, 0x81, 0x90, 0x78, 0xec,
	0x6f, 0xbe, 0x99, 0x9d, 0xef, 0x9b, 0x85, 0xf3, 0x5e, 0x9e, 0x67, 0xa9, 0x56, 0x2e, 0x35, 0x93,
	0xfe, 0x68, 0xec, 0x3a, 0xb9, 0x35, 0xce, 0xe0, 0x09, 0x93, 0xfd, 0x4a, 0x35, 0xb1, 0xfc, 0x8d,
	0x00, 0x03, 0xcd, 0x23, 0x39, 0x95, 0x66, 0x8c, 0x6d, 0x68, 0xa8, 0x35, 0x7d, 0x55, 0x63, 0x12,
	0x51, 0x1c, 0xb5, 0xab, 0xc9, 0x26, 0x46, 0x01, 0xc7, 0xc6, 0x8e, 0xbc, 0xe2, 0xd0, 0x2b, 0x56,
	0x4f, 0x3c, 0x83, 0xb2, 0xce, 0xcc, 0x74, 0x28, 0x4a, 0x9e, 0x2f, 0x1e, 0x28, 0xa1, 0xae, 0x66,
	0xdc, 0xd3, 0x9a, 0x98, 0x5f, 0xe8, 0x5b, 0x1c, 0xf9, 0x62, 0x81, 0x61, 0x0b, 0xaa, 0x6a, 0xc6,
	0x6f, 0xa4, 0x2d, 0x39, 0x51, 0xf6, 0x82, 0x35, 0xc0, 0x18, 0x6a, 0x43, 0x62, 0x6d, 0xd3, 0x7c,
	0xbe, 0x84, 0xa8, 0xf8, 0x7a, 0x88, 0xe4, 0x07, 0x5c, 0x05, 0x9e, 0x1e, 0x2c, 0x29, 0x47, 0x09,
	0x71, 0x6e, 0x26, 0x4c, 0xff, 0xb0, 0x76, 0x0b, 0xa7, 0x01, 0x7a, 0x1e, 0x2e, 0x0d, 0x16, 0xa1,
	0xec, 0xc2, 0xc5, 0x13, 0xb9, 0xe0, 0x7b, 0x9c, 0xd0, 0xe7, 0x94, 0xd8, 0x85, 0xd1, 0x44, 0x85,
	0x68, 0xe4, 0x00, 0x2e, 0xb7, 0x7a, 0x96, 0xeb, 0xdd, 0x43, 0x3d, 0x98, 0xcf, 0x22, 0x8a, 0x4b,
	0xed, 0x5a, 0xb7, 0xd5, 0x59, 0x5d, 0xac, 0xb3, 0x7d, 0xad, 0xa4, 0xd0, 0xd1, 0xfd, 0x89, 0xa0,
	0xb1, 0x71, 0x76, 0xec, 0x43, 0x65, 0x11, 0x03, 0xee, 0x9d, 0xd4, 0xbc, 0xd9, 0x59, 0x2d, 0x26,
	0x28, 0x0f, 0x70, 0x00, 0x38, 0xdf, 0x3f, 0xcb, 0x42, 0x0b, 0x18, 0xaf, 0x9b, 0x77, 0x27, 0xd2,
	0xbc, 0xde, 0xa3, 0x58, 0x0d, 0x7f, 0xaf, 0xf8, 0x7f, 0xf4, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x73, 0xa6, 0x68, 0xf5, 0xbc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApplicationMgmtClient is the client API for ApplicationMgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationMgmtClient interface {
	Create(ctx context.Context, in *ApplicationDetails, opts ...grpc.CallOption) (*ApplicationCreateResponse, error)
	GetAllApplications(ctx context.Context, in *GetApplicationsRequest, opts ...grpc.CallOption) (*GetApplicationsResponse, error)
}

type applicationMgmtClient struct {
	cc *grpc.ClientConn
}

func NewApplicationMgmtClient(cc *grpc.ClientConn) ApplicationMgmtClient {
	return &applicationMgmtClient{cc}
}

func (c *applicationMgmtClient) Create(ctx context.Context, in *ApplicationDetails, opts ...grpc.CallOption) (*ApplicationCreateResponse, error) {
	out := new(ApplicationCreateResponse)
	err := c.cc.Invoke(ctx, "/services.ApplicationMgmt/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationMgmtClient) GetAllApplications(ctx context.Context, in *GetApplicationsRequest, opts ...grpc.CallOption) (*GetApplicationsResponse, error) {
	out := new(GetApplicationsResponse)
	err := c.cc.Invoke(ctx, "/services.ApplicationMgmt/GetAllApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationMgmtServer is the server API for ApplicationMgmt service.
type ApplicationMgmtServer interface {
	Create(context.Context, *ApplicationDetails) (*ApplicationCreateResponse, error)
	GetAllApplications(context.Context, *GetApplicationsRequest) (*GetApplicationsResponse, error)
}

func RegisterApplicationMgmtServer(s *grpc.Server, srv ApplicationMgmtServer) {
	s.RegisterService(&_ApplicationMgmt_serviceDesc, srv)
}

func _ApplicationMgmt_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationMgmtServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ApplicationMgmt/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationMgmtServer).Create(ctx, req.(*ApplicationDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationMgmt_GetAllApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationMgmtServer).GetAllApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ApplicationMgmt/GetAllApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationMgmtServer).GetAllApplications(ctx, req.(*GetApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationMgmt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.ApplicationMgmt",
	HandlerType: (*ApplicationMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ApplicationMgmt_Create_Handler,
		},
		{
			MethodName: "GetAllApplications",
			Handler:    _ApplicationMgmt_GetAllApplications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ApplicationMgmt.proto",
}
